name: digipocket
description: "A digital pocket for your phone"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_link_previewer: ^4.1.2

  flutter_staggered_grid_view: ^0.7.0
  any_link_preview: ^3.0.3
  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  flutter_hooks: ^0.21.3+1
  dart_mappable: ^4.6.1
  equatable: ^2.0.7
  drift: ^2.29.0
  sqlite3_flutter_libs: ^0.5.40
  path_provider: ^2.1.5
  path: ^1.9.1
  image: ^4.5.4
  typed_isolate: ^6.0.0
  ffi: ^2.1.4
  flutter_rust_bridge: 2.11.1

  onnxruntime:
    git:
      url: https://github.com/varunbhalerao56/onnxruntime_flutter
      ref: main
  objectbox: ^5.0.2
  objectbox_flutter_libs: any
  rust_lib_digipocket:
    path: rust_builder
#  objectbox: ^5.0.1
#  objectbox_flutter_libs: ^5.0.1
#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.10.3
  dart_mappable_builder: ^4.6.1
  drift_dev: ^2.29.0

  objectbox_generator: any
  integration_test:
    sdk: flutter




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/onnx/jina-clip-v2/
    - assets/onnx/jina-clip-v2/model_q4f16.onnx
    - assets/onnx/jina-clip-v2/tokenizer_config.json
    - assets/onnx/jina-clip-v2/tokenizer.json
    - assets/onnx/jina-clip-v2/special_tokens_map.json
    - assets/onnx/jina-clip-v2/preprocessor_config.json
    - assets/onnx/jina-clip-v2/config.json
    - assets/LFM2-1.2B-Q8_0.gguf

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 800
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins-BoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic


objectbox:
  # Writes objectbox-model.json and objectbox.g.dart to lib/custom (and test/custom).
  output_dir: generated
  # Or optionally specify the lib and test output folder separately.
  # output_dir:
  #   lib: custom
  #   test: other