name: digipocket
description: "A digital pocket for your phone"

publish_to: 'none'

version: 1.0.18+19

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_link_previewer: ^4.1.2
  flutter_native_splash: ^2.4.7

  flutter_staggered_grid_view: ^0.7.0
  share_plus: ^12.0.1
  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  flutter_hooks: ^0.21.3+1
  equatable: ^2.0.7
  path_provider: ^2.1.5
  path: ^1.9.1
  image: ^4.5.4
  typed_isolate: ^6.0.0
  ffi: ^2.1.4
  flutter_rust_bridge: ^2.11.1
  pasteboard: ^0.2.0
  google_mlkit_image_labeling: ^0.14.1
  shared_preferences: ^2.5.3
  objectbox: ^5.0.2
  objectbox_flutter_libs: any
  onnxruntime:
    git:
      url: https://github.com/varunbhalerao56/onnxruntime_flutter
      ref: main
  intl: ^0.20.2
  http: ^1.6.0
  html: ^0.15.6
  url_launcher: ^6.3.2
  charset: ^2.0.1
  google_mlkit_text_recognition: ^0.15.0
  archive: ^4.0.7
  file_picker: ^10.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  build_runner: ^2.10.3
  dart_mappable_builder: ^4.6.1
  drift_dev: ^2.29.0
  objectbox_generator: any
  integration_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/glove/glove_vectors.bin
    - assets/glove/glove_vocab.json
    - assets/onnx/nomic-vision-v1.5/
    - assets/onnx/nomic-vision-v1.5/model_fp16.onnx
    - assets/onnx/nomic-vision-v1.5/preprocessor_config.json
    - assets/onnx/nomic-vision-v1.5/config.json
    - assets/onnx/nomic-embed-text-v1.5/
    - assets/onnx/nomic-embed-text-v1.5/model_int8.onnx
    - assets/onnx/nomic-embed-text-v1.5/tokenizer_config.json
    - assets/onnx/nomic-embed-text-v1.5/tokenizer.json
    - assets/onnx/nomic-embed-text-v1.5/special_tokens_map.json
    - assets/onnx/nomic-embed-text-v1.5/preprocessor_config.json
    - assets/onnx/nomic-embed-text-v1.5/config.json


  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 800
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins-BoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic


objectbox:
  # Writes objectbox-model.json and objectbox.g.dart to lib/custom (and test/custom).
  output_dir: generated


flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/images/app_icon.png"
  image_path_android: "assets/images/app_icon.png"
  remove_alpha_ios: true
  background_color_ios : "#FAFAF6"
  adaptive_icon_background: "assets/images/ic_launcher/ic_launcher_background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/ic_launcher/ic_launcher_foreground.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground_inset: 10 # only available for Android 8.0 devices and above
  adaptive_icon_monochrome: "assets/images/ic_launcher/ic_launcher_monochrome.png" # only available for Android 8.0 devices and above
  image_path_ios_tinted_grayscale : "assets/images/app_icon_monochrome.png" # only available for iOS devices
  desaturate_tinted_to_grayscale_ios: true # only available for iOS devices

flutter_native_splash:
  color: "#FAFAF6"
  image: "assets/images/app_splash_screen.png"
  branding: "assets/images/branding.png"
  branding_bottom_padding: 24
  android_12:
    image: "assets/images/app_splash.png"
    color: "#FAFAF6"
    branding: "assets/images/branding.png"
