[package]
name = "rust_tokenizer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
flutter_rust_bridge = "=2.11.1"
flutter_rust_bridge_macros = "2.11.1"
tokenizers = "0.19"             # HuggingFace tokenizer engine
anyhow = "1.0"
serde = "1.0"
serde_json = "1.0"
